'use client';
import {useEffect,useMemo,useState} from 'react';
import {columns,emptyFilters,filterError,selectRows,money,margin,growth,numeric,csv} from '../lib/financials.mjs';
import {suggestions} from '../lib/search.mjs';
const popular=[['AAPL','Apple Inc.'],['MSFT','Microsoft Corporation'],['GOOGL','Alphabet Inc.'],['NVDA','NVIDIA Corporation']];
const percent=v=>numeric(v)?`${v>=0?'+':''}${v.toFixed(1)}%`:'—';
async function getJSON(url,signal) {const r=await fetch(url,{signal}); const json=await r.json(); if(!r.ok) throw new Error(json.error||'Request failed. Please try again.');return json;}
function TrendChart({rows,currency,type}) {
  const [active,setActive]=useState(null);
  const series=[...rows].reverse();
  const values=series.flatMap(r=>type==='margin'?[margin(r)]:[r.revenue,r.netIncome]).filter(numeric);
  const min=Math.min(0,...values), max=Math.max(1,...values), span=max-min;
  const y=v=>175-(v-min)/span*145;
  const x=i=>70+i*(570/Math.max(1,series.length-1));
  const focused=series[active]||series[series.length-1];
  if (!values.length) return <div className="empty">No values available for this chart.</div>;
  return <>
    <div className="chart-readout"><span>{focused?.date}</span><strong>{type==='margin'?`${margin(focused)?.toFixed(1)??'—'}%`:money(focused?.revenue,currency,true)}</strong><span>{type==='margin'?'net profit margin':'revenue'}</span></div>
    <svg viewBox="0 0 700 230" className="chart" role="img" aria-label={type==='margin'?'Net profit margin by reporting period':'Revenue and net income by reporting period'}>
      {[0,1,2,3].map(i=>{const v=min+span*i/3;return <g key={i}><line x1="65" x2="665" y1={y(v)} y2={y(v)} className="gridline"/><text x="55" y={y(v)+4} textAnchor="end">{type==='margin'?`${v.toFixed(0)}%`:new Intl.NumberFormat('en',{notation:'compact',maximumFractionDigits:0}).format(v)}</text></g>;})}
      {type==='margin'?series.map((r,i)=>numeric(margin(r))?<g key={r.date}><rect x={x(i)-Math.min(20,200/series.length)} y={Math.min(y(margin(r)),y(0))} width={Math.min(40,400/series.length)} height={Math.max(2,Math.abs(y(margin(r))-y(0)))} rx="3" fill={margin(r)>=0?'#6d5ce7':'#cf5263'} opacity={active===i?1:.75}/></g>:null):['revenue','netIncome'].map((key,j)=><g key={key}>{series.map((r,i)=>numeric(r[key])?<g key={r.date}>{i>0&&numeric(series[i-1][key])&&<line x1={x(i-1)} y1={y(series[i-1][key])} x2={x(i)} y2={y(r[key])} stroke={j?'#16a590':'#6d5ce7'} strokeWidth="3"/>}<circle cx={x(i)} cy={y(r[key])} r="4" fill={j?'#16a590':'#6d5ce7'}/></g>:null)}</g>)}
      {series.map((r,i)=><g key={r.date}><rect x={x(i)-22} y="20" width="44" height="170" fill="transparent" tabIndex="0" role="button" aria-label={`${r.date}: ${type==='margin'?`${margin(r)?.toFixed(1)??'unavailable'} percent margin`:money(r.revenue,currency)+' revenue; '+money(r.netIncome,currency)+' net income'}`} onFocus={()=>setActive(i)} onMouseEnter={()=>setActive(i)} onClick={()=>setActive(i)}/>{(series.length<=6||i%2===0)&&<text x={x(i)} y="215" textAnchor="middle">{r.period==='FY'?r.date.slice(0,4):`${r.period||''} ${r.date.slice(2,4)}`}</text>}</g>)}
    </svg>
    <div className="legend"><span><i/>{type==='margin'?'Net profit margin':'Revenue'}</span>{type!=='margin'&&<span><i className="teal"/>Net income</span>}<small>Hover or focus a period to explore</small></div>
  </>;
}
export default function Explorer() {
  const [company,setCompany]=useState({symbol:'AAPL',name:'Apple Inc.'});
  const [period,setPeriod]=useState('annual');
  const [filters,setFilters]=useState(emptyFilters);
  const [sort,setSort]=useState({key:'date',direction:'desc'});
  const [ready,setReady]=useState(false);
  const [payload,setPayload]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[retry,setRetry]=useState(0);
  const [query,setQuery]=useState(''),[results,setResults]=useState(null),[searching,setSearching]=useState(false),[searchError,setSearchError]=useState('');
  const [searchOpen,setSearchOpen]=useState(false),[activeSuggestion,setActiveSuggestion]=useState(0);
  const options=suggestions(query,results||[]);
  const [filterOpen,setFilterOpen]=useState(false);
  useEffect(()=>{const p=new URLSearchParams(window.location.search);const symbol=p.get('symbol');if(symbol&&/^[A-Z0-9.^-]{1,20}$/.test(symbol))setCompany({symbol,name:popular.find(r=>r[0]===symbol)?.[1]||symbol});if(p.get('period')==='quarter')setPeriod('quarter');setFilters(Object.fromEntries(Object.keys(emptyFilters).map(k=>[k,/^-?\d+(\.\d+)?$/.test(p.get(k)||'')?p.get(k):''])));setReady(true);},[]);
  useEffect(()=>{if(!ready)return;const p=new URLSearchParams({symbol:company.symbol,period});Object.entries(filters).forEach(([k,v])=>{if(v!=='')p.set(k,v);});window.history.replaceState(null,'',`?${p}`);},[company.symbol,period,filters,ready]);
  useEffect(()=>{if(!ready)return;const controller=new AbortController();setLoading(true);setError('');setPayload(null);getJSON(`/api/financials?symbol=${encodeURIComponent(company.symbol)}&period=${period}`,controller.signal).then(setPayload).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[company.symbol,period,retry,ready]);
  useEffect(()=>{setResults(null);setSearchError('');setSearching(false);if(query.trim().length<2)return;const controller=new AbortController();const timer=setTimeout(()=>{setSearching(true);getJSON(`/api/search?q=${encodeURIComponent(query.trim())}`,controller.signal).then(r=>setResults(r.results)).catch(e=>{if(e.name!=='AbortError')setSearchError(e.message);}).finally(()=>{if(!controller.signal.aborted)setSearching(false);});},400);return()=>{clearTimeout(timer);controller.abort();};},[query]);
  const rows=payload?.rows||[];
  const filtered=useMemo(()=>selectRows(payload?.rows||[],filters,sort),[payload,filters,sort]);
  const latest=rows[0], previous=rows[1],currency=latest?.reportedCurrency||'USD';
  const revenueGrowth=growth(latest?.revenue,previous?.revenue);
  const filterCount=Object.values(filters).filter(v=>v!=='').length;
  const invalid=filterError(filters);
  function choose(symbol,name) {setCompany({symbol,name});setSearchOpen(false);setQuery('');setResults(null);setFilters(emptyFilters);}
  function download() {const blob=new Blob(['\ufeff'+csv(filtered)],{type:'text/csv;charset=utf-8;'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${company.symbol}-${period}-income-statements.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  return <div className="app-shell">
    <header className="topbar"><a href="/" className="brand"><span className="brand-mark">B.</span><span className="brand-name">Brook’s <small>Financial Observatory</small></span></a><span className="top-note">The numbers behind the business</span><a className="source-link" href="https://site.financialmodelingprep.com/developer/docs/stable/income-statement" target="_blank" rel="noreferrer">Data source ↗</a></header>
    <main>
      <div className="page-heading"><div><div className="eyebrow">RESEARCH WORKSPACE</div><h1>A clearer view of company performance.</h1><p>Explore financial statements. Find the trends that matter.</p></div></div>
      <section className="search-section" aria-label="Select a company"><div className="search-wrap" onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))setSearchOpen(false);}}><form onSubmit={e=>{e.preventDefault();setSearchOpen(true);if(options.length){const match=options[activeSuggestion]||options[0];choose(match.symbol,match.name);}else if(results?.length===0){setSearchError('No matching company. Try another name or ticker.');}}}><span className="search-icon" aria-hidden="true">⌕</span><input role="combobox" aria-autocomplete="list" aria-expanded={searchOpen} aria-controls="company-suggestions" aria-activedescendant={searchOpen&&options[activeSuggestion]?`suggestion-${activeSuggestion}`:undefined} aria-label="Search company name or ticker" placeholder="Try Apple, Microsoft, or Google…" value={query} maxLength={80} onFocus={()=>setSearchOpen(true)} onChange={e=>{setQuery(e.target.value);setSearchOpen(true);setActiveSuggestion(0);}} onKeyDown={e=>{if(e.key==='Escape')setSearchOpen(false);if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();setSearchOpen(true);setActiveSuggestion(i=>Math.max(0,Math.min(options.length-1,i+(e.key==='ArrowDown'?1:-1))));}}}/><button type="submit" className="search-go" disabled={!query.trim()}>Explore →</button></form>
      {searchOpen&&<div className="search-results"><p className="suggestion-heading">{query.trim()?'Matching companies':'Popular companies — pick one to explore'}</p><div id="company-suggestions" role="listbox" aria-label="Company suggestions">{options.map((r,i)=><button type="button" role="option" aria-selected={activeSuggestion===i} id={`suggestion-${i}`} key={r.symbol} onMouseDown={e=>e.preventDefault()} onMouseEnter={()=>setActiveSuggestion(i)} onClick={()=>choose(r.symbol,r.name)}><strong>{r.symbol}</strong><span>{r.name}</span><small>{r.exchange}</small></button>)}</div><div role="status">{searching&&<p>Looking for more companies…</p>}{searchError&&<p>{searchError}</p>}{!options.length&&!searching&&!searchError&&<p>{results?'No companies found. Try another name or ticker.':'Keep typing to search company names and tickers.'}</p>}</div></div>}</div><div className="quick-picks"><span>Explore</span>{popular.map(([symbol,name])=><button key={symbol} className={company.symbol===symbol?'selected':''} onClick={()=>choose(symbol,name)}>{name.split(' ')[0]} <small>{symbol}</small></button>)}</div></section>
      <section className="company-heading"><div className="company-identity"><div className="ticker-icon">{company.symbol.slice(0,2)}</div><div><div className="company-title"><h2>{company.name}</h2><span className="ticker-tag">{company.symbol}</span></div><p>Income statements <span>·</span> {currency} <span>·</span> {period==='annual'?'Annual reporting':'Quarterly reporting'}</p></div></div><div className="segmented" aria-label="Reporting period">{[['annual','Annual'],['quarter','Quarterly']].map(([value,label])=><button key={value} aria-pressed={period===value} className={period===value?'active':''} onClick={()=>setPeriod(value)}>{label}</button>)}</div></section>
      {loading?<div className="loading-state" role="status"><div className="skeleton-cards">{[1,2,3,4].map(i=><div className="skeleton" key={i}/>)}</div><p>Loading {company.symbol} financial statements…</p></div>:error?<section className="error-state" role="alert"><span className="error-symbol">!</span><h3>We couldn’t load these statements</h3><p>{error}</p><button className="primary-button" onClick={()=>setRetry(r=>r+1)}>Try again</button><p className="muted">Coverage depends on the data provider’s subscription. Try another company or reporting period.</p></section>:!rows.length?<section className="empty"><h3>No statements available for {company.symbol}</h3><p>Try another ticker or reporting period.</p></section>:<>
      <div className="section-meta"><span>Latest reported period · {latest.date}</span><span>{rows.length} periods available</span></div>
      <section className="metrics" aria-label="Latest financial summary">{[['Revenue',money(latest.revenue,currency,true),numeric(revenueGrowth)?`${percent(revenueGrowth)} vs previous period`:'Growth unavailable',true],['Net income',money(latest.netIncome,currency,true),'Profit after expenses and taxes'],['Net profit margin',numeric(margin(latest))?`${margin(latest).toFixed(1)}%`:'—','Net income as a share of revenue'],['Earnings per share',money(latest.eps,currency),'Reported EPS']].map(([label,value,detail,accent])=><article className={`metric ${accent?'accent':''}`} key={label}><span>{label}</span><strong>{value}</strong><small className={accent&&numeric(revenueGrowth)?revenueGrowth>=0?'positive':'negative':''}>{detail}</small></article>)}</section>
      <section className="charts-grid"><article className="panel"><div className="panel-heading"><div><h3>Revenue & profitability</h3><p>Reported results over time · {currency}</p></div><span className="chart-badge">{period==='annual'?'ANNUAL':'QUARTERLY'}</span></div><TrendChart key={`${company.symbol}-${period}`} rows={rows} currency={currency}/></article><article className="panel"><div className="panel-heading"><div><h3>Profit margin</h3><p>How much revenue becomes profit</p></div></div><TrendChart key={`${company.symbol}-${period}`} rows={rows} currency={currency} type="margin"/></article></section>
      <section className="panel statement-panel"><div className="panel-heading"><div><h3>Financial statements</h3><p>Explore the detail behind the trends. Values in reported currency.</p></div><div className="table-actions"><button className={filterOpen?'outline-button selected':'outline-button'} aria-expanded={filterOpen} onClick={()=>setFilterOpen(v=>!v)}>Filters {filterCount>0&&<span className="count">{filterCount}</span>}</button><button className="outline-button" onClick={download} disabled={!filtered.length}>↓ Export CSV</button></div></div>
      {filterOpen&&<div className="filter-area">{[['startYear','Start year'],['endYear','End year'],['minRevenue',`Min revenue (${currency})`],['maxRevenue',`Max revenue (${currency})`],['minNetIncome',`Min net income (${currency})`],['maxNetIncome',`Max net income (${currency})`]].map(([key,label])=><label key={key}>{label}<input type="number" step={key.includes('Year')?'1':'any'} value={filters[key]} placeholder="Any" onChange={e=>setFilters(f=>({...f,[key]:e.target.value}))}/></label>)}<button className="text-button" onClick={()=>setFilters(emptyFilters)}>Reset filters</button>{invalid&&<p role="alert" className="filter-error">{invalid}</p>}</div>}
      <div className="table-scroll"><table><caption className="sr-only">{company.symbol} income statements in {currency}. Click a column heading to sort.</caption><thead><tr>{columns.map(([key,label])=><th key={key} aria-sort={sort.key===key?(sort.direction==='asc'?'ascending':'descending'):'none'}><button onClick={()=>setSort(s=>({key,direction:s.key===key&&s.direction==='desc'?'asc':'desc'}))}>{label}<span>{sort.key===key?(sort.direction==='asc'?'↑':'↓'):'↕'}</span></button></th>)}</tr></thead><tbody>{filtered.map(row=><tr key={row.date}>{columns.map(([key])=><td key={key}>{key==='date'?<><strong>{row.date}</strong><small>{row.period} {row.fiscalYear||''}</small></>:money(row[key],row.reportedCurrency)}</td>)}</tr>)}{!filtered.length&&<tr><td colSpan="6" className="empty">{invalid||'No statements match your filters.'} <button className="text-button" onClick={()=>setFilters(emptyFilters)}>Reset filters</button></td></tr>}</tbody></table></div><div className="table-footer"><span>Showing {filtered.length} of {rows.length} statements</span><span>Summary and charts show all available periods</span></div></section>
      <div className="data-note"><span className="status-dot"/>Financial Modeling Prep <span>·</span> Fetched {new Date(payload.fetchedAt).toLocaleString()} <span>·</span> Provider responses cached for up to 1 hour</div>
      </>}
      <footer><span className="footer-brand">Brook’s Financial Observatory</span><span>Company fundamentals, in focus.</span><span>Financial data for research and exploration.</span></footer>
    </main>
  </div>;
}
